#!/bin/bash

if [ "$EUID" -ne 0 ]
  then echo "Please run as sudo"
  exit
fi

echo "Starting"

GREEN='\033[0;32m'
NC='\033[0m'

filedir=$(dirname -- $0)
Python=$(which python3)


if [ $(python3 $filedir/Python/InstallPackege.py) == 0 ]; 
  then echo "Flask needs install"
  pip3 install flask

fi

rm $filedir/Python/InstallPackege.py

echo "Flask Installed"

#sed -i -e "s/CHANGE/$SUDO_USER/g" $filedir/Python/Sakerhetskopiering

while IFS='' read -r a; do
    echo "${a//CHANGE/$SUDO_USER}"
done < $filedir/Python/Sakerhetskopiering > $filedir/Python/Sakerhetskopiering.t
mv $filedir/Python/Sakerhetskopiering{.t,}

echo "Changeed to username"


cp $filedir/Python/Sakerhetskopiering /usr/sbin/    #/usr/sbin/Sakerhetskopiering

echo "Flyttade filen"

cp $filedir/service/sakerhetskop.service /usr/lib/systemd/system/     #/usr/lib/systemd/system/sakerhetskop.service

echo "Flyttade filen"

mkdir /home/$SUDO_USER/Documents/Sakerhetskopiering_av_server

echo "Skapade filen dar kopiorna sparas"

systemctl daemon-reload

echo "Reload daemon"

systemctl start sakerhetskop.service

echo "Server started"

echo "${GREEN}All done and ready to use"
echo "remove instalation folder${NC}"

rm -- "$0"
